events { 
    worker_connections 1024; 
}

http {
    include /etc/nginx/mime.types;

    upstream backend_api {
        server backend:80;
    }

    server {
        listen 80;

        location / {
            return 301 /bms-suite/;
        }

        location /bms-suite/api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /bms-suite/ {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /bms-suite/index.html;
        }
    }
}